// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using itsmartplus.Models;

namespace itsmartplus.Migrations
{
    [DbContext(typeof(ItSmartContext))]
    [Migration("25620310061638_addthreetable")]
    partial class addthreetable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("itsmartplus.Models.admintable", b =>
                {
                    b.Property<string>("ad_id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("ad_lastname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ad_name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ad_pass")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ad_id");

                    b.ToTable("admintables");
                });

            modelBuilder.Entity("itsmartplus.Models.category", b =>
                {
                    b.Property<string>("cat_id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("ad_id");

                    b.Property<string>("cat_brand")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<byte[]>("cat_image");

                    b.Property<string>("cat_models");

                    b.Property<string>("em_id");

                    b.Property<string>("t_id");

                    b.HasKey("cat_id");

                    b.HasIndex("ad_id");

                    b.HasIndex("em_id");

                    b.HasIndex("t_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("itsmartplus.Models.employee", b =>
                {
                    b.Property<string>("em_id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<byte[]>("em_img");

                    b.Property<string>("em_lastname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("em_name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("em_id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("itsmartplus.Models.type", b =>
                {
                    b.Property<string>("t_id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("t_name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("t_id");

                    b.ToTable("types");
                });

            modelBuilder.Entity("itsmartplus.Models.category", b =>
                {
                    b.HasOne("itsmartplus.Models.admintable", "Admintable")
                        .WithMany()
                        .HasForeignKey("ad_id");

                    b.HasOne("itsmartplus.Models.employee", "Employee")
                        .WithMany()
                        .HasForeignKey("em_id");

                    b.HasOne("itsmartplus.Models.type", "Type")
                        .WithMany()
                        .HasForeignKey("t_id");
                });
#pragma warning restore 612, 618
        }
    }
}
